plt.subplot(3,3,1)
# plt.plot(index1, np.array(butterfly5['Total Delay']), linestyle='-', color='blue', label = "5 Bit Traffic")
# plt.plot(index1, np.array(butterfly20['Total Delay']), linestyle='-', color='orange', label = "20 Bit Traffic")
# plt.plot(index1, np.array(butterfly40['Total Delay']), linestyle='-', color='green', label = "40 Bit Traffic")
# plt.plot(index1, np.array(butterfly64['Total Delay']), linestyle='-', color='red', label = "64 Bit Traffic")
# # plt.xlabel('Index')
# plt.ylabel('Total Delays')
# plt.title('Total Delays')
# plt.legend(loc='upper right')
# # plt.yticks(range(0, 21))
# # plt.ylim(bottom = 5)

# plt.subplot(3,3,2)
# plt.title("Exponential Traffic")
# plt.plot(index1, np.array(exp5['Total Delay']), linestyle='-', color='blue', label = "5 Bit Traffic")
# plt.plot(index1, np.array(exp20['Total Delay']), linestyle='-', color='orange', label = "20 Bit Traffic")
# plt.plot(index1, np.array(exp40['Total Delay']), linestyle='-', color='green', label = "40 Bit Traffic")
# plt.plot(index, np.array(exp64['Total Delay']), linestyle='-', color='red', label = "64 Bit Traffic")
# # plt.xlabel('Index')
# plt.ylabel('Total Delays')
# plt.legend(loc='upper right')
# # plt.yticks(range(0, 21))
# # plt.ylim(bottom = 5)

# plt.subplot(3,3,3)
# plt.title("Center Hotspot Traffic")
# plt.plot(index1, np.array(hotspotcentre5['Total Delay']), linestyle='-', color='blue', label = "5 Bit Traffic")
# plt.plot(index1, np.array(hotspotcentre20['Total Delay']), linestyle='-', color='orange', label = "20 Bit Traffic")
# plt.plot(index1, np.array(hotspotcentre40['Total Delay']), linestyle='-', color='green', label = "40 Bit Traffic")
# plt.plot(index1, np.array(hotspotcentre64['Total Delay']), linestyle='-', color='red', label = "64 Bit Traffic")
# # plt.xlabel('Index')
# plt.ylabel('Total Delays')
# plt.legend(loc='upper right')
# # plt.yticks(range(0, 21))
# # plt.ylim(bottom = 5)

# plt.subplot(3,3,4)
# plt.title("Edge Hotspot Traffic")
# plt.plot(index1, np.array(hotspotedge5['Total Delay']), linestyle='-', color='blue', label = "5 Bit Traffic")
# # plt.plot(index, np.array(hotspotedge20['Total Delay']), linestyle='-', color='orange', label = "20 Bit Traffic")
# plt.plot(index1, np.array(hotspotedge40['Total Delay']), linestyle='-', color='green', label = "40 Bit Traffic")
# plt.plot(index1, np.array(hotspotedge64['Total Delay']), linestyle='-', color='red', label = "64 Bit Traffic")
# # plt.xlabel('Index')
# plt.ylabel('Total Delays')
# plt.legend(loc='upper right')
# # plt.yticks(range(0, 21))
# # plt.ylim(bottom = 5)

# plt.subplot(3,3,5)
# plt.title("Normal Traffic")
# plt.plot(index1, np.array(normal5['Total Delay']), linestyle='-', color='blue', label = "5 Bit Traffic")
# plt.plot(index1, np.array(normal20['Total Delay']), linestyle='-', color='orange', label = "20 Bit Traffic")
# plt.plot(index1, np.array(normal40['Total Delay']), linestyle='-', color='green', label = "40 Bit Traffic")
# plt.plot(index1, np.array(normal64['Total Delay']), linestyle='-', color='red', label = "64 Bit Traffic")
# # plt.xlabel('Index')
# plt.ylabel('Total Delays')
# plt.legend(loc='upper right')
# # plt.yticks(range(0, 21))
# # plt.ylim(bottom = 5)

# plt.subplot(3,3,6)
# plt.title("Poisson Traffic")
# plt.plot(index1, np.array(poisson5['Total Delay']), linestyle='-', color='blue', label = "5 Bit Traffic")
# plt.plot(index1, np.array(poisson20['Total Delay']), linestyle='-', color='orange', label = "20 Bit Traffic")
# plt.plot(index1, np.array(poisson40['Total Delay']), linestyle='-', color='green', label = "40 Bit Traffic")
# plt.plot(index1, np.array(poisson64['Total Delay']), linestyle='-', color='red', label = "64 Bit Traffic")
# # plt.xlabel('Index')
# plt.ylabel('Total Delays')
# plt.legend(loc='upper right')
# # plt.yticks(range(0, 21))
# # plt.ylim(bottom = 5)

# plt.subplot(3,3,8)
# plt.title("Random Traffic")
# plt.plot(index1, np.array(random5['Total Delay']), linestyle='-', color='blue', label = "5 Bit Traffic")
# plt.plot(index1, np.array(random20['Total Delay']), linestyle='-', color='orange', label = "20 Bit Traffic")
# plt.plot(index1, np.array(random40['Total Delay']), linestyle='-', color='green', label = "40 Bit Traffic")
# plt.plot(index1, np.array(random64['Total Delay']), linestyle='-', color='red', label = "60 Bit Traffic")
# # plt.xlabel('Index')
# plt.ylabel('Total Delays')
# plt.legend(loc='upper right')
# # plt.yticks(range(0, 21))
# # plt.ylim(bottom = 5)